### ISSUE TITLE
Why are BlogStream and OperationResult in the exception package?

### ISSUE THREAD

**Issue by twingly-mob** [xSAVIKx/twingly-search-api-java#2]
We guess these classes are used by jaxb and needs to be there for that reason.

https://github.com/xSAVIKx/twingly-search-api-java/blob/master/src/main/java/com/twingly/search/exception/BlogStream.java

https://github.com/xSAVIKx/twingly-search-api-java/blob/master/src/main/java/com/twingly/search/exception/OperationResult.java

**Comment by xSAVIKx** [comment]
Because, as I've seen BlogStream XML can be received only upon some exception happened.
I haven't found any description for Exception handling anywhere, so decided to do it on my own.

**Comment by twingly-mob** [comment]
Ah ok, thanks. We can leave it as-is.
