### ISSUE TITLE
Posts with content type != blog should not be in result set

### ISSUE THREAD

**Issue by twingly-mob** [xSAVIKx/twingly-search-api-java#4]
Looking at this test it seems like the item with content type newspaper is added to the result:

https://github.com/xSAVIKx/twingly-search-api-java/blob/2eb1db8234ea67f6ca44aafb619824af44f6b640/src/test/groovy/com/twingly/search/client/AbstractClientUnmarshallingSpockTest.groovy#L38-L62

The other clients ignores these.

**Comment by xSAVIKx** [comment]
Can be closed now.

**Comment by twingly-mob** [comment]
Looks good!
