### ISSUE TITLE
Test for testing all properties of a result

### ISSUE THREAD

**Issue by twingly-mob** [xSAVIKx/twingly-search-api-java#5]
There's a test that's almost doing this: https://github.com/xSAVIKx/twingly-search-api-java/blob/2eb1db8234ea67f6ca44aafb619824af44f6b640/src/test/groovy/com/twingly/search/client/AbstractClientUnmarshallingSpockTest.groovy#L131-L158

We'd like it expanded so that all properties are tested like we do [here](https://github.com/twingly/twingly-search-api-ruby/blob/746449e5157fc01dfc0792af62705053b2943eca/spec/parser_spec.rb#L22-L191).

**Comment by xSAVIKx** [comment]
Can be closed now.

**Comment by twingly-mob** [comment]
Superb
