### ISSUE TITLE
NullPointerException when getting posts from empty result

### ISSUE THREAD

**Issue by twingly-mob** [xSAVIKx/twingly-search-api-java#7]
To reproduce search for something that does not yield any search hits:

``` java
Query query = new Query(new UrlConnectionClient(), "the-key");

Result result = query.makeRequest("sadhjadsjasjdjasufysdiua", Language.English, new Date(116, 01, 29, 01, 00, 00), new Date(116, 02, 01, 23, 00, 00));
for (Post p : result.getPosts()) { // boom!
   System.out.println(p.getUrl());
}
```

**Comment by xSAVIKx** [comment]
It's common situation in Java.
It's commonly handled with [ApacheCommons](https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/CollectionUtils.html) usage, for example here, it'll smth like:

``` Java
Query query = new Query(new UrlConnectionClient(), "the-key");

Result result = query.makeRequest("sadhjadsjasjdjasufysdiua", Language.English, new Date(116, 01, 29, 01, 00, 00), new Date(116, 02, 01, 23, 00, 00));
for (Post p : CollectionUtils.emptyIfNull(result.getPosts())) { // boom!
   System.out.println(p.getUrl());
}
```

**Comment by xSAVIKx** [comment]
But, if you want - I can extend Query object with some check and return empty list if nothing was found.

**Comment by twingly-mob** [comment]
> But, if you want - I can extend Query object with some check and return empty list if nothing was found.

Hmm tricky. I think we would like a default empty list to make it as easy as possible for potential end-users.

**Comment by xSAVIKx** [comment]
Can be closed now.

**Comment by twingly-mob** [comment]
Seems to be working!
