### ISSUE TITLE
SearchPosts example does not iterate through complete result set

### ISSUE THREAD

**Issue by twingly-mob** [xSAVIKx/twingly-search-api-java#9]
We have the following [example](https://github.com/twingly/twingly-search-api-ruby/blob/4d053df7bf9e477e964cb01dcea174bfd156be02/examples/find_all_posts_mentioning_github.rb) to show end-users how to iterate from the "beginning of time" to present day. The API only allows for a maximum of 1000 returned posts per call and in this example the total is more than 1000.

The SearchPosts example only fires one request and does not continue to ensure that all posts have been retrieved. Maybe an implementation of the helper method `all_results_returned?` would be suitable here too to make the example cleaner.

**Comment by xSAVIKx** [comment]
I'll check your Rubi implementation and find out what could be done here.

**Comment by walro** [comment]
The same example is there for php, node and python too if you'd find one of those easier to read.

**Comment by xSAVIKx** [comment]
I've updated example, but forgot to add issue number, so please, find updated sources [here](https://github.com/xSAVIKx/twingly-search-api-java/blob/master/example/src/main/java/SearchPostsStream.java)

**Comment by twingly-mob** [comment]
Nice!
